version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    # This forces the Dependabot commit messages to conform to something
    # our auto-merge workflow can always cope with.
    # See https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/31#issuecomment-718779806
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
