# Needed for when dependabot makes PRs. Their branches are added here to the 'mdn' repo.
branches:
  only:
    - master

language: node_js
node_js: lts/*

cache:
  yarn: true
  directories:
    - client/node_modules
    - server/node_modules
    - cli/node_modules

# Because https://github.com/travis-ci/travis-ci/issues/9445
before_install:
  - npm install -g yarn
  - yarn --version
  # All nodes of the matrix will need and benefit from this
  - yarn

matrix:
  include:
    - name: linting
      cache: yarn
      script:
        - ./scripts/ci-lint.sh
    - name: client
      cache: yarn
      script:
        - ./scripts/ci-client.sh
    - name: end-to-end
      cache: yarn
      script:
        - set -x
        - yarn deployment-build
        - yarn end-to-end-test
