
# Ideally nobody should push PRs to the "origin" repo.
# Remove this once the repo is moved to the 'mdn' org.
branches:
  only:
    - master

language: node_js
node_js: stable

matrix:
  include:
    - name: client
      cache: yarn
      script:
        - ./scripts/ci-client.sh
    - end-to-end:
      cache: yarn
      script:
        - make build-content
        # Commented out June 6 because at the moment 'make deployment-build' will fail
        # - make deployment-build
    - yarn-audit:
      cache: yarn
      script:
        - make yarn-audit-all
