# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing Yari

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Display Node version
        run: node --version
      - name: Display Yarn version
        run: yarn --version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - name: Lint checking
        run: yarn prettier-check

      - name: Unit testing
        run: yarn workspace client run test

      - name: Functional Build
        run: |
          set -a
          source testing/.env
          echo "$BUILD_ROOT"
          echo "$BUILD_ARCHIVE_ROOT"
          echo "$BUILD_ALLOW_STALE_TITLES"
          echo "$BUILD_POPULARITIES_FILEPATH"

          yarn run prebuild

          node content build
          ./scripts/ci-functional.sh
